{
 "title": "ASP.NET OTEL Metrics Copy",
 "description": "Shows ASP.NET metrics from OpenTelemetry NuGet",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(process_runtime_dotnet_gc_collections_count, job)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(process_runtime_dotnet_gc_collections_count{job=~\"$job\"}, instance)"
    }
   },
   {
    "name": "http_client_peer_name",
    "label": "HTTP Client Pear Name",
    "query": {
     "query": "label_values(http_client_duration_ms_bucket{job=~\"$job\",instance=~\"$instance\"}, net_peer_name)"
    }
   },
   {
    "name": "app",
    "query": {
     "query": "label_values(process_runtime_dotnet_gc_collections_count, exported_job)"
    }
   },
   { "name": "query1", "query": { "query": "" } }
  ]
 },
 "panels": [
  { "title": "Process", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "irate(process_cpu_time{job=\"$job\", instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 10, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max_over_time(process_memory_usage{job=\"$job\", instance=\"$instance\", exported_job=\"$app\"}[$__rate_interval])",
     "legendFormat": "Memory Usage"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "stat",
   "gridPos": { "h": 9, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max_over_time(process_threads{job=\"$job\", instance=\"$instance\", exported_job=\"$app\"}[$__rate_interval])",
     "legendFormat": "Threads"
    }
   ]
  },
  { "title": "Runtime", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "General Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max_over_time(process_runtime_dotnet_gc_committed_memory_size{job=\"$job\", instance=\"$instance\", exported_job=\"$app\"}[$__rate_interval])",
     "legendFormat": "Committed Memory Size"
    },
    {
     "expr": "max_over_time(process_runtime_dotnet_gc_objects_size{job=\"$job\", instance=\"$instance\", exported_job=\"$app\"}[$__rate_interval])",
     "legendFormat": "Objects Size"
    },
    {
     "expr": "irate(process_runtime_dotnet_gc_allocations_size{job=\"$job\", instance=\"$instance\", exported_job=\"$app\"}[$__rate_interval])",
     "legendFormat": "Allocations Size"
    }
   ]
  },
  {
   "title": "Heap Generations (bytes)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max_over_time(process_runtime_dotnet_gc_heap_size{job=\"$job\", instance=\"$instance\", exported_job=\"$app\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Heap Fragmentation (bytes)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max_over_time(process_runtime_dotnet_gc_heap_fragmentation_size{job=\"$job\", instance=\"$instance\", exported_job=\"$app\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GC Collections",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "idelta(process_runtime_dotnet_gc_collections_count{job=\"$job\", instance=\"$instance\", exported_job=\"$app\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Exceptions",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(process_runtime_dotnet_exceptions_count{job=\"$job\", instance=\"$instance\", exported_job=\"$app\"}[$__rate_interval])",
     "legendFormat": "Exceptions"
    }
   ]
  },
  {
   "title": "ThreadPool Threads",
   "type": "stat",
   "gridPos": { "h": 9, "w": 4, "x": 16, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max_over_time(process_runtime_dotnet_thread_pool_threads_count{job=\"$job\", instance=\"$instance\", exported_job=\"$app\"}[$__rate_interval])",
     "legendFormat": "ThreadPool Threads"
    }
   ]
  },
  {
   "title": "ThreadPool Threads Queue Length",
   "type": "stat",
   "gridPos": { "h": 9, "w": 4, "x": 20, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max_over_time(process_runtime_dotnet_thread_pool_queue_length{job=\"$job\", instance=\"$instance\", exported_job=\"$app\"}[$__rate_interval])",
     "legendFormat": "ThreadPool Threads Queue Length"
    }
   ]
  },
  { "title": "HTTP Server", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "Responses Duration",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(http_server_duration_bucket{job=\"$job\", instance=\"$instance\", exported_job=\"$app\"}[$__rate_interval])) by (le))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(http_server_duration_bucket{job=\"$job\", instance=\"$instance\", exported_job=\"$app\"}[$__rate_interval])) by (le))",
     "legendFormat": "p75"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(http_server_duration_bucket{job=\"$job\", instance=\"$instance\", exported_job=\"$app\"}[$__rate_interval])) by (le))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_duration_bucket{job=\"$job\", instance=\"$instance\", exported_job=\"$app\"}[$__rate_interval])) by (le))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.98, sum(rate(http_server_duration_bucket{job=\"$job\", instance=\"$instance\", exported_job=\"$app\"}[$__rate_interval])) by (le))",
     "legendFormat": "p98"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_server_duration_bucket{job=\"$job\", instance=\"$instance\", exported_job=\"$app\"}[$__rate_interval])) by (le))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.999, sum(rate(http_server_duration_bucket{job=\"$job\", instance=\"$instance\", exported_job=\"$app\"}[$__rate_interval])) by (le))",
     "legendFormat": "p99.9"
    }
   ]
  },
  {
   "title": "Errors Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_count{job=\"$job\", instance=\"$instance\", exported_job=\"$app\", http_status_code!~\"2..\"}[$__rate_interval]) or vector(0)) / sum(rate(http_server_duration_count{job=\"$job\", instance=\"$instance\", exported_job=\"$app\"}[$__rate_interval]))",
     "legendFormat": "All"
    },
    {
     "expr": "sum(rate(http_server_duration_count{job=\"$job\", instance=\"$instance\", exported_job=\"$app\", http_status_code=~\"4..\"}[$__rate_interval]) or vector(0)) / sum(rate(http_server_duration_count{job=\"$job\", instance=\"$instance\", exported_job=\"$app\"}[$__rate_interval]))",
     "legendFormat": "4XX"
    },
    {
     "expr": "sum(rate(http_server_duration_ms_count{job=\"$job\", instance=\"$instance\", http_status_code=~\"5..\"}[$__rate_interval]) or vector(0)) / sum(rate(http_server_duration_ms_count{job=\"$job\", instance=\"$instance\"}[$__rate_interval]))",
     "legendFormat": "5XX"
    }
   ]
  },
  {
   "title": "HTTP Client ($http_client_peer_name)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 },
   "repeat": "http_client_peer_name"
  },
  {
   "title": "Requests Duration",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(http_client_duration_bucket{job=\"$job\", instance=\"$instance\", exported_job=\"$app\", net_peer_name=\"$http_client_peer_name\"}[$__rate_interval])) by (le))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(http_client_duration_bucket{job=\"$job\", instance=\"$instance\", exported_job=\"$app\", net_peer_name=\"$http_client_peer_name\"}[$__rate_interval])) by (le))",
     "legendFormat": "p75"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(http_client_duration_bucket{job=\"$job\", instance=\"$instance\", exported_job=\"$app\", net_peer_name=\"$http_client_peer_name\"}[$__rate_interval])) by (le))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_client_duration_bucket{job=\"$job\", instance=\"$instance\", exported_job=\"$app\", net_peer_name=\"$http_client_peer_name\"}[$__rate_interval])) by (le))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.98, sum(rate(http_client_duration_bucket{job=\"$job\", instance=\"$instance\", exported_job=\"$app\", net_peer_name=\"$http_client_peer_name\"}[$__rate_interval])) by (le))",
     "legendFormat": "p98"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_client_duration_bucket{job=\"$job\", instance=\"$instance\", exported_job=\"$app\", net_peer_name=\"$http_client_peer_name\"}[$__rate_interval])) by (le))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.999, sum(rate(http_client_duration_bucket{job=\"$job\", instance=\"$instance\", exported_job=\"$app\", net_peer_name=\"$http_client_peer_name\"}[$__rate_interval])) by (le))",
     "legendFormat": "p99.9"
    }
   ]
  },
  {
   "title": "Errors Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(http_client_duration_bucket{job=\"$job\", instance=\"$instance\", exported_job=\"$app\", net_peer_name=\"$http_client_peer_name\", http_status_code!~\"2..\"}[$__rate_interval]) or vector(0)) / sum(rate(http_client_duration_bucket{job=\"$job\", instance=\"$instance\", exported_job=\"$app\", net_peer_name=\"$http_client_peer_name\"}[$__rate_interval]))",
     "legendFormat": "All"
    },
    {
     "expr": "sum(rate(http_client_duration_bucket{job=\"$job\", instance=\"$instance\", exported_job=\"$app\", net_peer_name=\"$http_client_peer_name\", http_status_code=~\"4..\"}[$__rate_interval]) or vector(0)) / sum(rate(http_client_duration_bucket{job=\"$job\", instance=\"$instance\", exported_job=\"$app\", net_peer_name=\"$http_client_peer_name\"}[$__rate_interval]))",
     "legendFormat": "4XX"
    },
    {
     "expr": "sum(rate(http_client_duration_bucket{job=\"$job\", instance=\"$instance\", exported_job=\"$app\", net_peer_name=\"$http_client_peer_name\", http_status_code=~\"5..\"}[$__rate_interval]) or vector(0)) / sum(rate(http_client_duration_bucket{job=\"$job\", instance=\"$instance\", exported_job=\"$app\", net_peer_name=\"$http_client_peer_name\"}[$__rate_interval]))",
     "legendFormat": "5XX"
    }
   ]
  }
 ]
}